### ISSUE TITLE
没办法得到想要的Son属性值

### ISSUE THREAD

**Issue by caoDanLife** [Anduin2017/HSharp#3]
我发现在一个table中插入这样一段网页，

```html
<P>4.下列关于PC机外存储器,错误的是__________</P>
<P>A.移动硬盘通常采用USB接口或eSata接口,可随时插上或拔下(即支持"热插拔")</P>
<P>B.存储卡是闪存做成的一种固态存储器,所有存储卡的形状,大小,接口都是相同的</P>
<P>C.固态硬盘(简称SSD)是基于半导体存储器芯片的一种存储设备,其接口规范、功能及使用方法与普通硬盘几乎相同</P>
```

通过遍历每行的Son并不能直接得到p标签内的完整内容
![default](https://user-images.githubusercontent.com/29160809/49559424-bdf9e580-f949-11e8-9cf3-0315467ff7ff.PNG)

**Comment by Anduin2017** [comment]
Thanks for your feedback. I will test your code.

**Comment by Anduin2017** [comment]
We will fix it so you can access all content in the `<p>` tag. For now, please use `i.Children` instead of `i.Son`. For those content was separated into three parts and put as its `Children`.

`Son` is the same with `Children.First()`

**Comment by Anduin2017** [comment]
Your issue has been fixed. Please upgrade your HSharp version to `2.1.0`. And now you can use `.Son` to access the entire sentence.

Thanks again for your contribution.
