### ISSUE TITLE
html标签中的innertext长度小于2会导致“索引超出范围”

### ISSUE THREAD

**Issue by WoDeFaK** [Anduin2017/HSharp#9]
感谢up主的无私奉献，但是今天在使用过程中遇到些问题，麻烦up主帮忙看看如何解决，问题如下：

环境：win10, c#, visual studio 2019, 项目基于.net framework4.0

html字符串：`<table><tr><td>6</td></tr></table>`

此时使用`Doc["table"]["tr"]["td"].Son`获取数字6的时候报错：`System.ArgumentOutOfRangeException:“索引超出范围。必须为非负值并小于集合大小。`，研究了好久，发现如果html标签的innertext字符串长度小于2，就会报错。拿此例来说，如果td标签里的Innertext是60或者06就没问题。

**Comment by Anduin2017** [comment]
Thanks. Will do investigation.

**Comment by Anduin2017** [comment]
![image](https://user-images.githubusercontent.com/19531547/96569220-74c39c80-12fb-11eb-8eb9-55f6f88bbb8a.png)

![image](https://user-images.githubusercontent.com/19531547/96569244-7beaaa80-12fb-11eb-85f9-d6f59285bd17.png)

**Comment by Anduin2017** [comment]
Hi. The bug was fixed. Please consider upgrade it to the latest version:

https://www.nuget.org/packages/Aiursoft.HSharp/2.2.2
